spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:money_manager_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:FuAEcBdeBz}
  jpa:
    hibernate:
      ddl-auto: update