name: Run lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vue-project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        run: npm ci
      - name: Run lint
        run: npm run lint
